# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST http://localhost:5183/api/v1/DTCostings/mains
accept: */*
Content-Type: application/json

{
    "id": "VCO000000002DTSMC",
    "supplierId": "SUP0300645369",
    "status": "Active",
    "remark": null,
    "validFrom": "2023-10-05",
    "validTo": "2023-12-31",
    "annexLink": "https:\/\/bom.so\/czdGeB",
    "modeOfTransportCode": "DT-RailFCL",
    "modeOfTransportNameEn": "Rail FCL",
    "modeOfTransportNameVn": "V\u1eadn t\u1ea3i N\u1ed9i \u0111\u1ecba h\u00e0ng nguy\u00ean Container b\u1eb1ng \u0111\u01b0\u1eddng S\u1eaft",
    "uoMofTransportCode": "STEEL BOX 5T",
    "uoMofTransportNameEn": "40'Dry Cargo container",
    "uoMofTransportNameVn": "40'Dry Cargo container",
    "chargeCode": null,
    "chargeNameEn": null,
    "chargeNameVn": null,
    "additionalRequest": "Door-Port",
    "railServiceType": "Express",
    "airlineCarrierIata": "",
    "airlineCarrierName": null,
    "originProvinceCode": "70000 \u2013 74000",
    "originProvinceNameEn": "Thanh Pho Ho Chi Minh",
    "originProvinceNameVn": "Th\u00e0nh Ph\u1ed1 H\u1ed3 Ch\u00ed Minh",
    "originDistrictId": 647,
    "originDistrictNameEn": "Tan Binh",
    "originDistrictNameVn": "T\u00e2n B\u00ecnh",
    "destinationProvinceCode": "82000 \u2013 83000",
    "destinationProvinceNameEn": "Long An",
    "destinationProvinceNameVn": "Long An",
    "destinationDistrictId": 411,
    "destinationDistrictNameEn": "Tan An",
    "destinationDistrictNameVn": "T\u00e2n An",
    "originPortType": null,
    "originPortId": 0,
    "originPortCode": null,
    "originPortNameEn": null,
    "originPortNameVn": null,
    "destinationPortType": null,
    "destinationPortId": 0,
    "destinationPortCode": null,
    "destinationPortNameEn": null,
    "destinationPortNameVn": null,
    "volumeRangePerMonthUoM": "container",
    "volumeRangePerMonthName": "100 > 151",
    "volumeRangePerUoMuoM": "Shipment",
    "volumeRangePerUoMname": "Mincharge",
    "cost": 5000000,
    "currency": "VND",
    "leadTime": "Same day"
}